[package]
name = "surrealdb-migrations"
version = "0.4.1"
description = "An awesome CLI for SurrealDB migrations (provides commands to scaffold, create and apply migrations)."
authors = ["David Bottiau"]
repository = "https://github.com/Odonno/surrealdb-migrations/"
readme = "readme.md"
license = "MIT"
license-file = "LICENSE"
keywords = ["surrealdb", "migrations", "cli"]
categories = ["command-line-utilities"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.24"
clap = { version = "4.1.8", features = ["derive"] }
diffy = "0.3.0"
fs_extra = "1.3.0"
regex = "1.7.1"
reqwest = { version= "0.11.14", features = ["json"] }
serde_json = "1.0"
serde = { version = "1.0.144", features = ["derive"] }
tokio = { version = "1.26.0", features = ["full"] }

[dev-dependencies]
assert_cmd = "2.0.10"
