[package]
name = "surrealdb-migrations"
version = "0.2.0"
description = "An awesome CLI for SurrealDB migrations (provides commands to scaffold, create and apply migrations)."
authors = ["David Bottiau"]
repository = "https://github.com/Odonno/surrealdb-migrations/"
license-file = "LICENSE"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.24"
clap = { version = "4.1.8", features = ["derive"] }
fs_extra = "1.3.0"
regex = "1.7.1"
serde_json = "1.0"
serde = { version = "1.0.144", features = ["derive"] }
tokio = { version = "1.26.0", features = ["full"] }
reqwest = { version= "0.11.14", features = ["json"] }
